version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootinho
      MYSQL_DATABASE: rooto
      MYSQL_USER: nodinho
      MYSQL_PASSWORD: rootinho
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
 
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db


volumes:
  db_data:

networks:
  default:
     attachable: true

